//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medkeeper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Medkeeper.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medkeeper.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEDKEEPER.
        /// </summary>
        public static string ApplicationTitleCaps {
            get {
                return ResourceManager.GetString("ApplicationTitleCaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medkeeper.
        /// </summary>
        public static string ApplicationTitleLiveTile {
            get {
                return ResourceManager.GetString("ApplicationTitleLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents have been disabled by the user. Check Settings in phone..
        /// </summary>
        public static string BackgroundAgentsDisabled {
            get {
                return ResourceManager.GetString("BackgroundAgentsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete latest intake.
        /// </summary>
        public static string DeleteLatestIntake {
            get {
                return ResourceManager.GetString("DeleteLatestIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete latest intake?.
        /// </summary>
        public static string DeleteLatestIntakeMessageBoxTitle {
            get {
                return ResourceManager.GetString("DeleteLatestIntakeMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete item?.
        /// </summary>
        public static string DeleteMessageBoxTitle {
            get {
                return ResourceManager.GetString("DeleteMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codermee.
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        public static string DeveloperTitle {
            get {
                return ResourceManager.GetString("DeveloperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dose:.
        /// </summary>
        public static string Dose {
            get {
                return ResourceManager.GetString("Dose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit latest intake.
        /// </summary>
        public static string EditLatestIntake {
            get {
                return ResourceManager.GetString("EditLatestIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No intake registered.
        /// </summary>
        public static string EmptyIntake {
            get {
                return ResourceManager.GetString("EmptyIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to history.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to intake.
        /// </summary>
        public static string Intake {
            get {
                return ResourceManager.GetString("Intake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest intake removed..
        /// </summary>
        public static string IntakeRemoved {
            get {
                return ResourceManager.GetString("IntakeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake is saved..
        /// </summary>
        public static string IntakeSaved {
            get {
                return ResourceManager.GetString("IntakeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item has been deleted..
        /// </summary>
        public static string ItemDeleted {
            get {
                return ResourceManager.GetString("ItemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is saved..
        /// </summary>
        public static string ItemSaved {
            get {
                return ResourceManager.GetString("ItemSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest intake: .
        /// </summary>
        public static string LatestIntake {
            get {
                return ResourceManager.GetString("LatestIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If switched off, the app won&apos;t be able to update the live tile with info..
        /// </summary>
        public static string LiveTileUpdatesInfo {
            get {
                return ResourceManager.GetString("LiveTileUpdatesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile updates on/off.
        /// </summary>
        public static string LiveTileUpdatesToggleTitle {
            get {
                return ResourceManager.GetString("LiveTileUpdatesToggleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Feedback] Medkeeper.
        /// </summary>
        public static string MailSubject {
            get {
                return ResourceManager.GetString("MailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codermee@hotmail.com.
        /// </summary>
        public static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark intake.
        /// </summary>
        public static string MarkIntake {
            get {
                return ResourceManager.GetString("MarkIntake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a name for your item..
        /// </summary>
        public static string MissingItemName {
            get {
                return ResourceManager.GetString("MissingItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing name.
        /// </summary>
        public static string MissingTextMessageTitle {
            get {
                return ResourceManager.GetString("MissingTextMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No intakes to remove..
        /// </summary>
        public static string NoIntakesToRemove {
            get {
                return ResourceManager.GetString("NoIntakesToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device doesn´t support background agents..
        /// </summary>
        public static string NoSupportForBackgroundAgents {
            get {
                return ResourceManager.GetString("NoSupportForBackgroundAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string PinToStart {
            get {
                return ResourceManager.GetString("PinToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
